### ISSUE TITLE
[Alle Patienten] /patients/query returns 405 Method Not Allowed

### ISSUE THREAD

**Issue by JonasCir** [ImisDevelopers/1_011_a_infektionsfall_uebermittellung#144]
Request URL:https://api.imis-prototyp.de/patients/query
Request Method:POST

Request Payload:
{"firstName":"","lastName":"","patientStatus":null,"id":"","order":"asc","orderBy":"lastName","offsetPage":0,"pageSize":10}

Response Payload:
{"timestamp":"2020-04-06T10:50:42.662+0000","status":405,"error":"Method Not Allowed","message":"Request method 'POST' not supported","path":"/patients/query"}

**Comment by jonathangpk** [comment]
@MichaelSp 
Client wurde von master neu deployed, server nicht
![image](https://user-images.githubusercontent.com/33756680/78551971-eaa46280-7806-11ea-824e-da9400d0c8ec.png)

**Comment by MichaelSp** [comment]
```
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'logging.level' to java.util.Map<java.lang.String, org.springframework.boot.logging.LogLevel>
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:364) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:324) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:308) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:238) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:212) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.logging.LoggingApplicationListener.setLogLevels(LoggingApplicationListener.java:398) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeFinalLoggingLevels(LoggingApplicationListener.java:338) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.logging.LoggingApplicationListener.initialize(LoggingApplicationListener.java:289) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEnvironmentPreparedEvent(LoggingApplicationListener.java:246) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.logging.LoggingApplicationListener.onApplicationEvent(LoggingApplicationListener.java:223) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127) ~[spring-context-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at de.coronavirus.imis.App.main(App.java:12) ~[classes!/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) ~[app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) ~[app.jar:na]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) ~[app.jar:na]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) ~[app.jar:na]
Caused by: org.springframework.core.convert.ConverterNotFoundException: No converter found capable of converting from type [java.lang.String] to type [java.util.Map<java.lang.String, org.springframework.boot.logging.LogLevel>]
	at org.springframework.core.convert.support.GenericConversionService.handleConverterNotFound(GenericConversionService.java:321) ~[spring-core-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:194) ~[spring-core-5.2.4.RELEASE.jar!/:5.2.4.RELEASE]
	at org.springframework.boot.context.properties.bind.BindConverter$CompositeConversionService.convert(BindConverter.java:170) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:96) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:88) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.MapBinder.bindAggregate(MapBinder.java:64) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.AggregateBinder.bind(AggregateBinder.java:56) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.lambda$bindAggregate$3(Binder.java:415) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:572) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder$Context.access$100(Binder.java:513) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bindAggregate(Binder.java:415) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:376) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:320) ~[spring-boot-2.2.5.RELEASE.jar!/:2.2.5.RELEASE]
	... 27 common frames omitted
```

**Comment by MichaelSp** [comment]
das sieht nicht gut aus hier: https://github.com/ImisDevelopers/1_011_a_infektionsfall_uebermittellung/blob/master/server/src/main/resources/application.yml#L47-L48
Ich kann das leider gerade nicht fixen, würdest du das übernehmen?

**Comment by jonathangpk** [comment]
bootup oder runtime error?

**Comment by MichaelSp** [comment]
crash-loop. Kommt beim bootup

**Comment by jonathangpk** [comment]
fix ist raus

**Comment by jonathangpk** [comment]
works
